name: localpulse-dashboard
region: nyc

services:
- name: backend
  source_dir: /FIU_V2/localpulse_clean
  github:
    repo: SquizAI/fiu_hack
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /api
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: WINDY_API_KEY
    value: "5jVQqxUM3iRPuBsAXVG8PtE0ORCktGCf"
    type: SECRET
  - key: CORS_ORIGIN
    value: "*"

# Domains will be auto-assigned by DigitalOcean 