name: localpulse-dashboard
region: nyc

services:
- name: api
  source_dir: FIU_V2/localpulse_clean
  github:
    repo: SquizAI/fiu_hack
    branch: main
  run_command: node server.js
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: WINDY_API_KEY
    value: "5jVQqxUM3iRPuBsAXVG8PtE0ORCktGCf"
    type: SECRET
  - key: OPENAI_API_KEY
    value: "sk-proj-8SLq8VB_Fy9Uq2b1mKJ8nOaLKJQGLH_vIzUe8VgFqKJfSdYfZaG9cMnBxTrQwSdFgHjK"
    type: SECRET
  - key: MAPBOX_PUBLIC_TOKEN
    value: "pk.eyJ1IjoibWF0dHlzdGpoIiwiYSI6ImNtYzlkMHd0czFwajUyanB5ajNtb2l3d3QifQ.kioIyWE_H_3em-jpvKDiwA"
    type: SECRET

  - key: CORS_ORIGIN
    value: "*"

# Domains will be auto-assigned by DigitalOcean 